---
- name: Hardening tasks
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: >-
        Download issue and motd files from cisagov/ansible-role-banner
      ansible.builtin.get_url:
        dest: /tmp/{{ item | basename }}
        mode: "0644"
        url: "{{ item }}"
      delegate_to: localhost
      loop:
        - https://raw.githubusercontent.com/cisagov/ansible-role-banner/develop/files/issue
        - https://raw.githubusercontent.com/cisagov/ansible-role-banner/develop/files/motd
    - name: Harden system
      # We do not control the names of the role variables.  This
      # is the reason for the noqa comment.
      ansible.builtin.import_role:  # noqa var-naming[no-role-prefix]
        name: konstruktoid.hardening
      vars:
        automatic_updates: true
        fallback_ntp:
          - 169.254.169.123
        issue_template: /tmp/issue
        journald_storage: persistent
        manage_timesyncd: false
        manage_resolved: false
        manage_ufw: false
        motd_template: /tmp/motd
        ntp_servers:
          - 169.254.169.123
        sshd_admin_net:
          - "0.0.0.0/0"
        system_upgrade: true
        packages_blocklist:
          - apport*
          - autofs
          - avahi*
          - avahi-*
          - beep
          - git
          - pastebinit
          - popularity-contest
          - prelink
          - rpcbind
          - rsh*
          - rsync
          - talk*
          - telnet*
          - tftp*
          - tuned
          - whoopsie
          - xinetd
          - yp-tools
          - ypbind
        packages_debian:
          - auditd
          - cracklib-runtime
          - libpam-pwquality
        packages_redhat:
          - audit
          - cracklib
          - libpwquality
          - python3-dnf-plugin-post-transaction-actions
        packages_ubuntu: []
        pass_max_days: 365
        pass_min_days: 7
        sshd_max_sessions: 4
        suid_sgid_permissions: false
        umask_value: "027"
    - name: Delete local copies of issue and motd files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      delegate_to: localhost
      loop:
        - /tmp/issue
        - /tmp/motd
