---
- name: Import base image playbook
  ansible.builtin.import_playbook: base.yml

- name: Import automated security updates playbook
  ansible.builtin.import_playbook: automated-security-updates.yml

- name: Import UFW playbook
  ansible.builtin.import_playbook: ufw.yml

- name: Import OpenVPN playbook
  ansible.builtin.import_playbook: openvpn.yml

- name: Import CISA CDM playbook
  ansible.builtin.import_playbook: cdm.yml

# TODO: Remove this when and if that becomes possible.  See
# cisagov/skeleton-packer#301.
- name: >-
    Import playbook to install prerequisites for the Netplan
    configuration fix
  ansible.builtin.import_playbook: install-prerequisites-for-netplan-configuration-fix.yml

- name: Import AWS playbook
  ansible.builtin.import_playbook: aws.yml

- name: Import hardening playbook
  ansible.builtin.import_playbook: harden.yml
