---
collections:
  - community.general
roles:
  - name: amazon_ssm_agent
    src: https://github.com/cisagov/ansible-role-amazon-ssm-agent
  - name: banner
    src: https://github.com/cisagov/ansible-role-banner
  - name: cdm_nessus_agent
    src: https://github.com/cisagov/ansible-role-cdm-nessus-agent
  - name: chrony_aws
    src: https://github.com/cisagov/ansible-role-chrony-aws
  - name: clamav
    src: https://github.com/cisagov/ansible-role-clamav
  - name: cloudwatch_agent
    src: https://github.com/cisagov/ansible-role-cloudwatch-agent
  - name: crowdstrike
    src: https://github.com/cisagov/ansible-role-crowdstrike
  - name: freeipa_client
    src: https://github.com/cisagov/ansible-role-freeipa-client
  - name: konstruktoid.hardening
    src: https://github.com/konstruktoid/ansible-role-hardening
    version: v2.0.4
  - name: htop
    src: https://github.com/cisagov/ansible-role-htop
  - name: nvme
    src: https://github.com/cisagov/ansible-role-nvme
  - name: openvpn
    src: https://github.com/cisagov/ansible-role-openvpn
  - name: pip
    src: https://github.com/cisagov/ansible-role-pip
  - name: python
    src: https://github.com/cisagov/ansible-role-python
  - name: remove_python2
    src: https://github.com/cisagov/ansible-role-remove-python2
  - name: systemd_resolved
    src: https://github.com/cisagov/ansible-role-systemd-resolved
  - name: ufw
    src: https://github.com/cisagov/ansible-role-ufw
